language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: ULFhMAZl/pWwsIVEO6tv/MScx5pbA8YhYwQC58irnyAGrJO6+GhrNL2RsHn0JLE1r68tU8/dMOAIbLYbL0PLs1Y1fFtktAyX4UHEB4WekDsmXYHCyiRJlHbFFpLT8ZREoPzR1OQ5aKblrLeFOwdbQZSGR9vKQaTcl1v82HSdVML5tvPnz//Zr/b+kUZZLGvrge5a1w4SYIi7mv/TyqBLUOL9pPi4gSS94M9yHzuaKot9uVOPicm1jb2NygK5ENdu0xk2+i/aeH/pw1kPRJMo6dzRgLwZXG5ZcMph1HO90xqLB/zwr6OBAKBgtuqkNhqS0z/pWE/YkY9LSO846SYYpR3In0+8SwHJoyr8C3Weax0GieFDgC46/Mj7L7ZhWwRsDYiYLVthzMoqev+aU5xTHdshyz0taG6EGrElAOurBowKvQ4O9XLBkhd47JL4XA+fgY9C+iJCjFWu6AeIaZu5PkrB0RM7fNOhDLLt8S3y2wBz4zAhigMYuNuBh9RPygHvly26zmx8XiejQJViGvx3hltwWY7aGUpgVicAo3t3XXKlfKUQZRDhW12b9JSy/czlfD3p0m2/vQ9VM02vxmwOqMmUNKI8UwRbKOgxYyioOCzVXUOXgiBIwpn90y6t+mFv9Amm49nuOt8C+ykWCaquSqcw/UwQ2+Vk6xbVRTMoj/I=
  - secure: o5i1g69biufxxure/j7Al4R2OP/F8wPQljQh9JwpaGbaIznrYpEuWUoG0ghREJSMPzE7nBrVWltflEMpg2hAWVcwoNxVe+rIHB4dcFxj4jsqMavsfuQB7ThbQneBcKxd3L+fN8Fs7mTSA0wXYaCOf0K7MCvlRPZLLBUXg459A2SMlEIKQxrmHS4VJtYL/YXBbMJD3zEkeRnsXk2w+ntWl0qQZFEBbBOppwMQ41qd05yicgm5pAE6XcS8N/5kukCX+e1zKzlcg6QiiVHkMmYkXa433lZ1mWA/V25tLmDYBV2wsFS153AieX7q35DdVr5Y8CjrSyI2L/Cl9RIOT802dYydlr1LgBcVH0HyYMBniM/mh5eXFGEp1quZhJ7h6rFNJ7VmE+/7xY2F6avtEkSARYMLa8qvPyoYdOvvNaSquZwoo1wIPcek6Q92hGkWOdUd89/fyGcX2GobjKCxf0mEBsVxUZAllmFNKkiwiiFivp4PKBTzNabm2aBwvxVk3gxGHrCyMnOFfvDX9f/2b8aKrOoEkYSXr6zRDPUnuv+xMyIM4m1dIJFl80+rWhxA1qYGpo+WL/Eu5U4cvpc+uip/oao83FrFTlrw/YTFPIwFyw0TGMwYpcyLshPkbaVLaz0vEBvToPwDNNIGSNWSQLSv+otI6DaCHCoaID8vNpjo2Lc=
  - secure: IRekAFw94+CZeU6zLSMyty1mUhYjFHe7lD5sBmVhK42kZYIU+l/EXMaugPRBg/jL4Q5ORANRx97hzMkz9LgyFziO6fP7JNVX0Nj5Qm8dGylzp5miWrD31RbYlv5WbomKm4ogSivVRw30lHQ8NTnrx6FPN2gS5TN7al6bJ0iG21bkFm6Rt6GvR80ivznq1eg8o3FJVhalgGIyjPZpbZRcy2+irVr5/Pl7/UPj0xiejlghOwHciC7zq7EWdrN/WvoBMppMAOWgveCXX9KZZzCRL6vahtJ2CReAf6fPalKrGYsuF9w6dzyy1kMpbRlksY3Z+JUq9/AVjXMz3NOmeVglgmAl2MS3Ccl8d6BKsky+HwqURc7oGaBk9GOOWhIlGwI4k+oBC645cW87V+oiF67RK3cJ3vsGJ2ETdAFKnWYQhFkyCaB329xgQ6s4rMdEVVmatc3OG2sDAO30DipNKuoRP9Wr6oZ9YIz1iNk/LgVNS8aYpkTk9JNKU+BQI6OhYN/xqwizFEobYMLvnMBDvLVzepZheS4+k7k+3uwCUhRF/jhajWojj8tw6bWYSB0sJQwZwmvRx2ZJh8UDeWeLJtqTC1FVvthnGMEZ/FhzAtkqJ4M35J31V1+sqPdvCVUWkC9La0YeuagpWfD4iDKAy8hDUbomxLyc0rFEHTQc5aEN21U=
  - secure: eqdRD/A4kQkHUXjTCh3//FuYXn1+YTKSO1E2r49JQ5/iRc+FwjUhQP74C/Jg1RlnAuTTaFf2J/CPMFsLxQFSe7S1BS7BvvwZZaPL7bIPyJKLpGi6aYn3ocnGGs7WTOzWV9QJyKYgbfalW0/I0pz7uTu/iJ5ujuy1lzsupBSETGJ/Z3dX0+edyA81FTY6dPVKn5XoX+U9f5tgyAg/E4+ZOD/wSk7/j5WWCzi9AFoilb6YNQNhtowQAxUbSA5UdNa4BwifFwPAxxTiadCnDkOLkNyQucRmCxXwYaWaNK39CthIIoRPiG0f+WzD/kwshjtsSeFtdi9hHoxHm4aNJlzQ65MxgJsbDJukiPo/opQw6Tw39VtfJKnE2bumUkJm+EfG3lp/YfMu2a06c1mg2XO1DxmqhTe5X3XO+/YivNnVz4UjvdKbegkt2eu5DUO9NSL2HPb/T3ONcVY/R2tJNeFgaaeGJInP7oUfL8qUcGzxNqnIH+DB2I0EuiMIj4mFMLSYWDQ1J+TV6MKYJhxVZItNtAIRt/yKIOwrKZXtlGffbKuLdOld8jghRlXfYRuMvEJdj7AtaShlz7lTGM5QruiOb84K8MkfOPVv+RoKFcZCVl3lLSdEc/Y484/ib+I61ncJl9TZzd8fW8ck1YTIRrtX75ihHWpYdIohPya4i8S8NcM=
  - npm_config_PGCON=postgresql://example:serverless@cp1qkyovnmreyp0.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp1qkyovnmreyp0.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://5mngdl53hg.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=just-use-gmail-for-now
  - FRONTEND_URL=localhost:3000
  - GMAIL_ADDRESS=ctxfloodstestmailer@gmail.com
