language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Locally
    before_script: yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: yarn start-express-server & yarn test
  - stage: Deploy to AWS
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn rebuild-and-deploy
  - stage: Test against AWS endpoint
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      tests."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn test-on-aws
    after_script: yarn; yarn rebuild-and-deploy-with-tons-of-crossings
env:
  global:
  - secure: hFpE3ZXuMeAJbnCCWXod4dfVcJTutq9dAeUCiKJlc7uzybg7pchFs2xmx4W4BietEpA54/1Q7hq3xMvNFwPK3pxsrgK6+tsxdFmLTNKJTtJqdIwXiddd5OPwi64p8Boj902UJ5Wl91xnAFOQrJ5C544lKvavf7irjwkyCTeCXf/E3KQZ2ANJCYhMiyt6ATGU2hvyNoi3NIpioQRFa9LTjAsk3kDfKpVHmOaGhRshRhSLtMnuJxv+NZSyjurYeAf4zwp3EHPG6WU+zZITNyXcobaGj0yukbUem5f2xZ/91tlwOR/cRmtRXgrQjS0SXRdQ8zguxepwtWg9YrkkedTs6hNWtoLCCES39bdLdEhuRj3fA8QxWrY10qSBArnP7qiOyuATwKeH0dFRunx9YKfqnlF6LIrrcstfh6lj6hBJaQXrPkK1fTd2e7fOfiSUaTfOFfY6AB2rZWmE/AQmK1IceBGtmRGt6Td6OcWTQy+nKRuMJyjP7OOpU7ysmdcOaCdbvxNK/UUJM1K3DAS/x0ZUE1dBm7makuiBq1YOShI06972JfP8lZqdBFaAtoeEj3HpeIH2MiZyLpY7FkWFEzpUHA4lIGdD3nNtUyNWF5LaXYGxlaqf3OjR7OC/J3jbTqNG3jafC95cIV3Q7uyfFi5rCInWco4fUEVJykg8Uavu29g=
  - secure: CCUCfhs2KKhBmC9OFO8RFl1RDwOarVNZH7cEBo2L4dTKTQ8X05mzYSGH1YOPtttAdqPelBHsIdRMfL4s29Hwf9A6znu4eqTm37/2vYCq/b8VGz5yjep8E8XUWMjz5Vp92t8JS9+ziEHHpo46+s9XuMRBSKeWal5W19FaIO9xBFYI+oyDXUiPBhtW5e3LjdZ2edxkzIBsE0rIquzdJl2zPGa/AYd5/V0LsWXg0gFRLntwRsxLZher0sHoogK6ad8BT6fEc3u1Wntt8XfD7Y0E9DE7biDPLrtgaq53vUpXcuncd/aUa+Kyv1L/Ijw7KSLANSFqCfaEXPX6fc97Mv79Xvx5hNEbw6WsiP+FIVwfzcLf9mA/gBmJGtCb95LhAAQuVTJo2pGczEkcWckeQPnDbomDEfuOuLfAG7ZP5eyXMrbCSZjsFmYyeDJAZ5lmxUoP1ZdvIvx4UQhELv5euhP8OQquBaVytfTEVMi+o3dKAv0fmb7Yd4eBMFjQhxWGVOknvLwKSnrHdUjk8w0ATlHOwLsLPQva4AaXkJWJdM3VpS3MVCO0NHGEKKGIZfHmEmbL8JXAY6vwLCcXXwR0ABcpLNwglrZ9EtR6RzN5PhryA4AnF87Xt4Gs6Nbh2yjdNHGwpD4Wn8hBjRe0CwdxcMJgUXQ3bvrLSwrD28VoDvV4KoI=
  - secure: l1OhWgJVaxustMNmF33NTRIVQWNZ92la/prZFVc2p9iniKSFjeopi+1i3TYs/O578jl/p6Vc3nkMiwcJLqNqHXjkct1zlXYj8L5C7c/UVGdQlxmodZAQAs58lOVP1XBaTp2VSgNdpZ3avseKCKnhE8Oh9VXB2shEGfRIG1b0iFpRvUvZMtKjMlXOCBxpSK+thXuBQYR+3Qg853OSNwbMCSNUdJ2glf356WjBgMN5YQU1z+JvVXVG842wNf++aXbjABlVA+kBDmitaIx2g//WQTFwYcE8w+AA86OAXPr4yJBQNrzwELoO09AwQisvOiVDBehfYQ9nqkqQwJqonCvsdRK327ivDh7sJjQjMaMHagv/6gaQ7JurwJPcZ5yqCKfDiyXyI9OME1RnsNuYEFTRYee/BEgUW4Xyrw8Gl4y1pGShcYufp8wbmbRJ2WUG3tFfwvp1bSCPUcrUIpoUZLG9RLUCwWP6AFBNurRTnXoOkejoOnKP4qdcgYAtyHRh9S87Zhg6QaEAPv0Wb7Ux1furOix6v0gH4KQdB5V9lTPvRlGT6vE7fl3noWvhQDRgtzdGgut7N5fUp2Fi5O2WHAyFS/QqqU7uEZWhkGdGMcj6m6WOuVL1HjZCJrYGw3n5zvjRSg087m8KGg0Kqgr1aWXsP8PYVR7+nKP36CNrwBqJMIY=
  - npm_config_PGCON=postgresql://example:serverless@cp8xcft6pkj7qq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp8xcft6pkj7qq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://hvjmr4h5r1.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=set-up-travis
  - FRONTEND_URL=localhost:3000
