language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: L+DmDh3diLpC+k2ihJD4etKOy4bMzU8LyxuqfQwLfnivsQZ4ighM+ZevK2oZOhzLRnuzHm38UiJt5N+wljR/tOdx3gce1kmDLr5Is3UY9UwiYgZSUmCbJMIIWAaPnRyC267J2NjDMjAjX6fM9EFKk3SMPS1EYih5aRUeqY3R/zvb77+c3dynMvoKWvla7gb3KHhUauIhHWJ1wN34qjDiLSiMCzy2Grjmsghc9Y3yMsBlYPqeK/vCGZEGppkqpASTqkZYVy9ZrLSIFpc62wr+rmlLxIH+qGupeiLQFgkRsc+C2v3p4fneo/GfKyP212Q8VVNMN4D+34Y++vKhfvvmVxZw+uAf/9JmdaqPczk89KUFnDA0dEa3bvXQSe0gMuh8HWHQ4GkIpYfmA7vcUr5fau1HV2mIC9k089WxnJmhkd9dbuJwcPFwmbQzEUpF4s/wcJrkPpLjnb7Ea+pcW4uLm+Udx3JGsqkXj7m82qykud+6ekqFFT8D9eX++7/dyMP/wcQyPFc1HdCgNsbRcOIcT0TTeprh+4QXHpugovPBZY8+BN1WhwWkvQp8+OvdmTg/dGSJPk2KRUP/nmpaTf6Nd79y/7q343gt4uGflH6QNhcv3KGWwqq1jDFKqJ9n6NpFSALNyKhZbp8AYziYYPlwRTuqgeFpgJ20YNe6/bX/hEY=
  - secure: YKbc2203kGKNWYbIFCiFI5Ou1qZgKJZL0rF1A114ocj5O+DNVla0KvbIM8qzEEZSw/Hjy3VcYaRt5iVPwk5PucB1hy+kXFfLaPmAosX8ApY64Mt9u1QIGkKfEQbuPwQV9mzqJtgxd8UAYyktbl3xMeUfTktuZIgqGmGXxC0TrTg+4Nzbzbho3VWON1po1o6aLOMzuH0FJGlt0V3/0BY1DouXZe60T4GbsE/wwcn1I+Zef0KUXxd3hA+RFMqLRjQ2pQ2jcrnRi4U0CFbQzEvQ1FyTdn0rJ1bB6lFZTfw/06cpABWVgm2CU0bZvfm1I5PYaYtVvyCYQSI3FTusr0lV291++ilRVhbPhw8afq/RNKI2wPbj8wlbhp+/5JxV/djAoU4ipm8e3/hwQPdyF8+NiRLjdTHp2AxV02UQ/GAbgNUoDnFn0wXN9bvAOzzQSIpnS9TcfcMICjP4bbRO0T2aAymllPYBls1ysxrkqAZABy5IhmOZmcN4/B+eTMkPWnrtRNkRFWbtv5u28kJ5v3FcTYFF6B8CjYpiZ+PtFOv3JAUW+GDpsRVckMLdzH9dWdux5puk+o9pLeOSo59tFRi+1hcqK8thKltAPUwc7st+g5sXieqsOAhXI5yEx2WNFokzeUtaJ+JAGAqT1TlHba/jVgxVnOUy+47JaD50CARrcfo=
  - secure: r0UYGxF1d7yp2ZkMO0mupYVt1X5dU725qCzbJxw3Q6e+c4p4AqQ3bq7qXmBv00MwVUscnDwZqswqoYWC89mNnXpY5V9mnFdpu9v/qKiCA3l+MsJBlDQS4SWJMAsQDsxlYWhqbmq5qUH5b0liI2KjdKmXe71hbQB8NJEKYnM5ngNudLFEu6ei/DOH9r0qr8x61V/870wSkw7PfnhGq0Mcu5M4gpg2NHwm5ShTeBzQgE1JoT/pUvPJnczmXAzftxIQD8TmasrOagQF+VFKWjkffiwm9Pn8vEt7FmzcR7tg6Ntu+3p+QfzgHwfNR+RGiWNqZB8sMXLkmVpYkzMYhFutnDZOHRO9bbmNbQ7m/pKgYxq3Q9+7LVxK6j5R96qQOnWUPI28aykOQYdtbhSXnwI0RX3wxaYc9b9nmYQHg8QiQCGaknpmhjIz6q1RdlDZ9RObBfrH4x6qeIJeOPlMtPsrA3eHAlvfVIXGgCjV5Oc/k5j1X3lHiEkhAEJ446NY/C6DQyE9k8bws8ZTd+wKaSg/cz2HXcUtYnIoPrG93NkHva5GaeT0Rm35uWCaj2aAFtZzr4s8ZsSCwVCW3tYoVjyYSy0L6RMvjHIc0eoZB5mGrVy2n5Mhy0PdjC4PUTITRctn7f11p5Q8zlDIocNsH/f/OCuBkB26tzPQ1FRXiB9jTCw=
  - npm_config_PGCON=postgresql://example:serverless@cp1k9j9pzb9nyoq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp1k9j9pzb9nyoq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://2omhorg3mc.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=master
  - FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com
