language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Locally
    before_script: yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: yarn start-express-server & yarn test
  - stage: Deploy to AWS
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn rebuild-and-deploy
  - stage: Test against AWS endpoint
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      tests."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn test-on-aws
    after_script: yarn; yarn rebuild-and-deploy-with-tons-of-crossings
env:
  global:
  - secure: l7pKM5R+pFtODhjdJKK1HB/X77GvisA8vOUHAfMdNHy95aHsBMtFy9qOe467ytlt0Voh+MklY9Gq3eTA9FMEQ28pLMOoiHe+LNH4JFe8yMSMH0ULFtQS1CdAz3B24k0GEVDK0JCp1Oul5cp1Wp174w7G5ilBFdNcI3TJFcI6dq7fwZbhJ5MZAvwWgs2lKdYgjpDq+cDyOHWqLDDXBpLuB1hlaB6yTPe56IG9/Ddk9gkTvufcgNiQSwmmhq0FgMaxNBJzBBWIq5L+PMUIUDTD3Am/174K62z7phd/qxhD48AHXXkXI//yezS3vXBThQhOQ3bW9Cv5BYc1gRm4iIwwmJ2Skp180kLMkCoIIsJ4Lc7++rbp3C03DnLPG7I4l8VW9rtRgp3PuX/bnFYCh5jHLnh4U+blHEjNP/4UdX5PgFouRykeTVOq2foPfHxDkZZWe8Rh/Q8zPhyFWlcssrqOmvHmV9V/K9DsR22jNgQoNG2n695wlcnPvjpsWgmu6kS8OHie9nvmYKU/ns3VifFDnASm6Bv1kvxda21Y410hExRt+LHMmdWu5c+SEMx/o3cnzXxzWvA0NVqGBjxBl+jWTb1djLBANsEwIxcijKhMhqf3DwwIKkerKg1Ylt1vFg087fAb++MNVLvQnzbKWQwoHsxc+YLBb9G66HhXCpzuv9M=
  - secure: paFmdTiFX32o2YcCC72D0hno0/o9Ccuu9UybTb1te45vo1ajEPWdX6FrmYMiKuUQLRr5jgS4kOzOK2gjBgddNCHA3KiWnR+MqmbzXAFK/n1Tr+htl1V8X5+lwuGUf/stNd7jzl2xNP0a88EcJ13TBzlMSk5i/J8HMYzA8W4kWAreIBSWG3eRt7epONws9Dfx0h6Q+7gwhrsrWsEmqYgS3CRkttHltGkNScrWeTt+ZGgDE4Tgz0LwtP3CV9mwiu2BTrTDckYdgdhcV+h7xtWeT8jnFVph8VogZ7Biv+dbxqayonS8zP0YrcIV5B0SXPgxQsMVvdJZwdCmfTRDj/EkP9ZINMY1P1UadvruL8M5D3p66TxsQVA1FgGZqvJ7/fJgt13f/CRabiQLqjyZd1K3DnCl4I0EbYPQ+vHbyzdw6UmeSy7FH9hlF56L5vEhEhBorbVVEtrKbRRxLlHk2I6WqdQYPF5JdmpoMsNJMERvydhi7bv8VHt/CxspOVEL1EvR5maQG3Vscxb5aGeT2joanw8nA1FXnffoJiziwzOzo7ufskrkIMv3Nbd4I60nvL10TFRsLM28bnaTk3FskulSzswBgrp3Fh3a4sJP2D1tXsT5SMh89kJ2dcwrygTiXs8VgSfqDmcRSi8o688lqKVslHHgeHi2bCTsf4wgAxsSxU8=
  - secure: FkB/TwlSrOOTz1EjwlM6GaNFwl9p9Nvhtph0N+WTv7hTWhOCULiNG2FzG8su37RUxsHF/5m9SWbmMd0FvNmbCwVRqh9MFnutbmDzEyVfgmh0xzQazH+Hy7MdQnP1jLwVq5GGRwx6N9zctFHwf6uzolcIyj88U5myxXQXUbwDB07NqXOAVh1KfnB2x5E4GK/xwrHRlWrMyxEa2NfjTqxgZMmOKKbA2sTW60IpwZhCjiTGl66BO/d5/TRyDwIPJphSi8mARcabTrO7IkDy3tcsvgxlDq/Qwn0BHLvNEMpA8LJiL77N4DoUc0eq7gaVxDMnPC4t64RRC5AKFAoJYhkTp/9tE8dLUXznPKszZT8JcYsDDObwQYmiYVji7hsLgauu8TJ1pclXg/yuk5tMpoVuK3mKW/KrdlpJfa0XDX7etOurgYhAWfO8MS/BVXpw7CNLvtj/mxDgilsjUStOVSPHL7/UHFAZqSnUbhXKgi4CVxCOOOTFbmxPDDQ79vvJm0gUV0PL4ywhuAUmMotY6mhEyKYlsmokd9fyXkU2obWfcr1l+05IP3uu+R8ILT3M88dkJCwsGwpVG6xfOEcbInwKAr8qRMzeNPeZLPNeP7PaGyEUU53mRB0yUJ9FyqTNz5uL/P1GDLRbOT2AgEgDUYF+W7KhKU3S/h5fVExSYtilLN4=
  - npm_config_PGCON=postgresql://example:serverless@cp1k9j9pzb9nyoq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp1k9j9pzb9nyoq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://2omhorg3mc.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=master
  - FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com
