language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
before_script: yarn; yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  before_script: npm install -g serverless@1.25.0;
  script: yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: tWhjjsByB7zCBblIUqDbbnGhd4GkvpuutcbG6klj5o4+Fq9Y769KCDUyuEP22VbqbhaBfoVJhENj8lPTT1nu8d4khcgTWwmeKlO9PHG2cu4GuDqB/fCdGh9YAD1/rWXLbAmEM3lvBlndoqi2lAEQvZAIwq2MU6ejf2f/zKepIndM4FHmvseLjfniojCi2goGnWerk9jo8pjdaTJdtJ+0O9YGzfucKqV9UmjURXb6UR5VJu3z/xgT6nBFmQkhO8SILrD3dROoWTV+cwF0JuhyRg32hRgC3QoBD48N1OngrUNLzf/wrOyMZbCxZavXSwFobDaS2qDr346KGudcq5F5XjMCsnaDkjCZpDkQ7bSF3kpKQDBHwee1gSaUMRzAShYb4hJFeSHMlA8xA7sgbc1lypE53n8Un4LXBWz7SkRMw0gY6fYoHL9dOnXZzXwbuEvN/hGWKX0F0asUFHv1vgBnichr1U1tCOuufHylPI8kXBQI9345GZa90bFGc2Nji7rfzrMAH4D1iRJGy+8/B88nsYjJ+tyw07euTqrDSWyoAfN26EvQcPEnI1BjbhumDjkDVIM4zlG0jxRh+tIaYWxTepQP/X8UKIxMS6WAKCG/g8NRHBhShOGeV8L+Rd+HH/ldqIujEeOgv7P5QgMdJHPIz7uR41Bx9N0ea1n/obf0Tm4=
  - secure: MYXetZkvbTCca4HzvB/SuDvAzA6VEFaliwHpSqOGAVzxr749acamKaHbLlO+95XL3QrgiqhTXi28e8IW+wdzfFLd2HfX37JOTjA/NLkvACjkELqectWVzdzhaeETp38M6RAop96bi7uSiIPEL/b38Pe0mtVPFHb9ZY086N3zQRIEwYjXJLosiapIgRXcyboLcVChpp6HM4t/wzPUCtthmzNLrMBFB+xSb0yPyh9ZD21ybpqT7WrixEDJ8iuK9GQR67GRt9XTSL0scyeaiX3HU0KCUgMVYLXtiS6oIJNvMJrellIx0BdiPiJao61aqQApGQAim6/8oleN2DIvcS3ohsDsOgGLK7U6fMVmYZM/UmYMMtLsiQQdBsCYdy7WnpTovUl66tW7zSvTw7gB8Gf9iqZIWaX2QP6b4kyP8NceXJjXsanszf9NVCDMia4JIS0WF93LwTLpXqd9Xynf1b0gBCI7o9Vw/UwQ3JjldBC7rGXVBoNIq3dAKfvkpzDnClCff6VtRBizo/lfJicw2IJmWJpGKRShb9xL1nB4HtzkY1ddKy8pHjjJFkLF98NflswhohTQCqP5IQjj862ecryoYC/Gd5xBx5SRLUWnR9jZs7yVOlwDMxgZi/+nShoQ/YtbAvqJ4oFj2BED3k/VqDlw7VJ97+J2BENzqtBUlL+nPcA=
  - secure: kmrIExQQgxc7VBpJgF2iKtj3XRrDtOPKaTpR2yp2e4DQQNBeJKbIMH7dPke9E9KrgN5YgzLwbdHJvzaSOsEyZ8PaBnpB1P7raDwbX3WePcBfdXnCO5tFEudWiN1wbt9skU+RhzyggsXgtluHSMcotUqWNEKonGcHkNU+Nt/yphdwDPkQrN8tLxxcSBzmPSE0sd3C6as8ZNV0zTKNyqvDPPziq8+H4BwhJMpXSmuKR2Zn54w5iSn6pfmWPvfpShR8QXfjF4HRCWYTg36BMjVVkBb6LdeqF/DwBIRl+Iqz7gOnMSIDxNF7sM5e3PEkYAIotkSsFN/QrFyZRYAtvA3jriLh2he0zLuqEdsE5zvhuUpjNd8o/oHgyeLYciYj1KvGSqSNt/unsTO3ud0lrH7SPjlm8MBtmBCojFsl8MJsfOM3D0JC8WPC7SmkEd7Z63qOk1FGkYRc+eHYfiYnROslVbX4vybSxw6/KcEVwow/eo9cfjCG/AH46DYRVGeSHvof4cAIqkWrwkxY5jKp6HRXMitOqvpi3OAKKfciIvPmZwFqvNIGRQmVCy1pKlZUxgSiH9yEwkJqvxC1y4oDrX2xxbRZYfycv7q6X+kDSHRcnjA8/rFIu2z1Ez6ceoBAMXMV7mqvaPAcA+fCkWSOS3tuRR65V3CWburCUJaELL/shAA=
  - npm_config_PGCON=postgresql://example:serverless@cp1dajoku32cegv.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp1dajoku32cegv.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://qt9foeymrf.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=dev
  - FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com
