language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Locally
    before_script: yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: yarn start-express-server & yarn test
  - stage: Deploy to AWS
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn rebuild-and-deploy
  - stage: Test against AWS endpoint
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      tests."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: yarn; yarn test-on-aws
    after_script: yarn; yarn rebuild-and-deploy-with-tons-of-crossings
env:
  global:
  - secure: caZyJzBksAtiebdGCKy1pJgMUf5Z3elZQJ3u4YNJUCmDaUNY2CxhSZDbiY7hSiVnyJPoWWQ0zWri8h3iIoS8nGc1+kxLSsHMDl028rrjX0N7EsjYZk43kFb0jPnj+c3mAYtnnBSKmAKn4+G4CBQ6Ih5wCHSIPeobLEaZRmFLSIlFHgUGoyMDCEYNL1M8LBstXfIFJ/CQZOCoH8Mp97QWqMWUVrxAGRKr9I4SZA+f+izHcuV30uIpbpar93blQS+yvKaGD6pbfnXieOLK+YzFGjTPqBklsXWcBX3kfMdThB14rHr9BqWa3CfHYd298cB1w1Ok6Xdf6Nu0Eu0pV4O0eAq6v3oJAMUvSSIK7zmpbsDQ1NHDN862Qu1tPxQtW0u0F4TSm9HiYH26Obtq4wzXNFkanT9RuzGYtKGfcwgpGbOtHKXtZ5ZJuxpoSaYMxroSPUgsJVmftTwIB+HjUiFurxVAP1clMw+GUQstaCMSwXxU0gA2/+TnODkHluFXgw6KfmomznK44bljoU0Cq9yFBqoWQdMAN92n3RjaZZFOglosnICH9Vcc7Q1252wG2DohyTHL0HlXYoXQPcI5qUK/c2G7E1nXHLCKu5kguqWovcj4cH8ivV013x9EG8LGdtfBnXSWO24ilK5hHO6BVLfW7f4TgGQHE7qpBaAVHEGZDDs=
  - secure: YaoVWmcnUe0LbPOpnqVqsVdnuj4k2euJJZgGAkjK0dMxPqyX/FvkIxmMPAwD06KBKazEWPZC8uoZR4hV+348NoQVjp87G0D9F9IwlaZnwIXrAts/5Co5yjZo2fSOXnO0kcQhll5xum3w+cRGXZPGnRCRC7Fjs1o9+7WDDM6MLd6tE/Z16n4EhSq+rvAARe830H6YS5icicNY5LWJtIbR4uQBkygENHKx6ZPxcniFRBC0xK93Cen6HVbIQPXiLWHZL/G74kuPPfZh8GqPFoNp7gIihOoy4S5dbIawUUN3U9g9gIL+GQoBh8Rv7tpJ/qUyduCxZ9+4RJKaRpYuQx1iiI4iR38c/IwRhgftj/CqaovN9gw2qj6s3iI8VImtTo8JmPfm6Bjaa6vGDSWktZhHcKCvBkgzvaVfD/unQEb9mEjYxEGIldoYII0UVcYYAm5lG9Hwj+5QxnbT0RqHZN5Xvxr/j6HOxjVZE0NgxuLJ5o5vp1Is+34ERTT/z6AekpAQ5A5x44UoITiDSkWRXZJFD6Z7BqlFHeDIpw1ilp4nplH0LVwnPCrw0mKfURnuZopcjhr+IRBqMVvBdF2r0+88gZabAEr2shkwoIz3k2lbGocU80N5GFh5J6ZFqAgkagXXk7HrCRbPuPsZ120qR/i6//V5lujdsHWnUiYhcXlHa1s=
  - secure: Ll1MmJp8NGq9BewYvFIYzgBgQnfcwU1jc8ou7wfBTFJJ8xXpYUujfgF9wL2rjAW3YiXRqljYgPXPtC/kmtDpuy3qqeCdBpWf0hafLADJiJFAHHgT4FnGNBJl2L1NpkpwdEbfH9RrE12DOzznxfzohYzIQBlnGzONU00zPAzbSjYJ7lw+ucnmaFrU2WEe6AWxaOSLvZhKwq6AOeeiNhl6lfI9yq1u+vml9NGOCzOntOp2ov/4NmaTj6soU/kYksxXq8vAy+J90ek9sTTz6FfCK7CQT2wTIcbyecuSPxOu6640Ie94CdvYIwszKdx8PctynFqRLkSzqKhnU4qdx11k/YXB+nSWUm1BQhkJMNBd+6xBy4WE+8NNOgBJQmdgpJxK/qLN5ePFv9GrkaEksGLDocgH5UbwJ9PU8RgIjt+9A1Ccn+KQ796acGUK2dTVPtRFpuXQLsHypl42joRAIYfsAxmdQh14ZQz9q+hCi8GU8kDmyK8jGfNHO1mE5n2/acZPuH6PGyZ8rlCzvchrN85ppTnyd4p2h73EcddAKirMhl9golOH9dV6X0eSMNccJRslxejtqeew4dOEzzwGjfnXYjK/ZRMesWZ+w0FeB488Upw6s+e6BfhMdSN1CbQrzXxK56RKnErvTEeXGr3O2A/LKktiugzRjLUQ0QxQhN/pHHk=
  - npm_config_PGCON=postgresql://example:serverless@cp8xcft6pkj7qq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp8xcft6pkj7qq.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://hvjmr4h5r1.execute-api.us-east-1.amazonaws.com/dev/graphql
  - FRONTEND_URL=localhost:3000
