language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: vC9w+owjBuivi73VXVhTh2WNvuGhFXrAVsU0bzf5aqvEwNQG+2g49iMJOYFi28YxA4GG3SLOmNLHT5FtpLohHFgUv1e0Q/JrAiS22TEWbIA1PhjbuOBknqxR2DhZldveeI3/yrfEl1wfgUPFsdBaaCW3+1oTC72rb2Vs8No+vpw2IW01wvx9ofEZM0ofStRVy0PLQ9h9407wFg1sZUzxMiNr/cyV/7dgLSe7ns+ivur6UNZHwbnW5QRnmRJaHqOU/j+HBRPAYVQlHhjQT5EHv7PNnfLnlPyFgipYsw/3/tV7hkKqVHpyzHnyXgYIlfen3P5RWg6+qM8kaa05tsjHPGXCqnAf1OE3BpItRmXH35oZJvDfXnVaDp5qDl0vYQpNbVm8hZmXJKS38P0AQRIiV8woXYKSXuZ5KHjJBq6h6t5ad8e00W1hG4w3dI3jTcGGmHQgwWsq0X5oLFSz0uW7jVnGuOGsG7UXLU2fiqjannBiMes/7VZjint+wSnrilg3y+DMhC2iow5xo/CtMbVBkiX1GMQ2mjwfRs/zxkUE4WSZWtO6o1W5TVI7ZLvbFCOiD18gBtzu8F8kta+wCfewxPR5aeGSlnEXwMXm3EeOpzZ1IelNmVk3hgUgBHWhZpA0f3ly+7YTvEKfu9+mFISUOvPkOmTqn9SnUTXqdhYUOoY=
  - secure: DgJKFjFEzx6DMQkeE4yMeeMiWwbyrW8Di0mhtHasBb5qMHaNCatPCpIZxDzkIl5EcWKOdTUjek2J6rybXlFfQMlhuWqjFLmGoKY+G1gbfCwBr/Iz1VO9Q2Z/+HFV/GU1b6Es/KPkW2aLk7bi1YkOp9mbvIgaDO0HlTlOs45EjC1q2TVb/T4xjbq1QnnkcKjF1hIXIy1xrQTtnI+aj1DQzzgohUH84lqRKrYdsv5x7R+soyxjbofEqqjSPjuBx9u1gYGGZbOByZY7C+OrMPQx9hwjOmR0nV/WW53w0yU9okYGyPX3qDvLBsggWPVkKDcoJmxQQy7x2gHc5kqm46JD/sZHslQsWUZwEq8HPoml7EIO7sFVjSHpCkePuh7vWXYYgz8M6jdkuakXjRPAU9Q/ckF6IsXaD09UwbYZzW4s7gwiHYT8bU/cI575IO4jje0Z2KWDQz2SiUSREv+AYTpfdz/k/nR6QG99E2uld2nFNMZPIfzFz97sDMuGZ69UiOTHU5/S10ZyI0qU2g+uaFuMLZm1sjs/eR95fOYk+q1N0wh6Sh+J+X36x4HNbKmqnlG0IyPCo71RpPVfeWRHA4Knw0FYdlNtTk6n8a+SiQQpemiptmERzpHqOg21ROwgEIQTmxYM73k7CyxNfd69Lk9SXeF7C1HNI7D5EuoymDAqlqk=
  - secure: KINhg9+X1772u6DL28dU+qQOeTrR4VXz0lg7W4Kyc272DlRG8PaS0MVgUYSxvTmJNi/XatfXXgeUpMxg9GLX3AU2j7LyKVr1znW4+/cSuRR3EjxVF0csVCOTQbtll6zuEEEM/Gm9euBNH5gpS+r4qqIJdWyPsia9TKHh8ZKpAT3onXnY9alVWE2a9TC217+3HT1TWqFMVq/5RwiRPJu4+RwVxDTxUnAcoidJ1Wd5KLlv2ZLQ/uk9f5/PUXI0dv5qRnV7jvXguzAej9L2CyxUkthzZgkYp7RXxfr/GyskJzmLUaOmChvRvIi8xcvIdJH0pooTh6HDb18ZibWkWq2UJe2Gd+HlQSHMrtRAHZqEUb6GrT2O94K1627rRZRWI1bTqpC+W8rkfLh122GXZDt0kVWnHO0mKbpyvXITnFWfo2WJn1+pb3h/3g/oOlQFJ2lGVcdZ5GtoZ+0koAofKwJmf2TRDOYXXLXUB6fpA6lhabTEC3RL6KJh+MexaSRS2K4XZCEZqj4cG6LI59swJFzVccPJPO2aDbx70JD3YS0VEDg6TAg+a4XW6WzfIYl+/ugOqzfnFcM39sDYxDWpk/uffYg3I6P4SaKnZPVUS8KJAglWb6W9zTBY7TYdUeQdtQiRjyLR2ZPEFxxcTfkY3T5mm1s07uOL8VoVmITNDf4n0FM=
  - npm_config_PGCON=postgresql://example:serverless@cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://fzd0rh62c5.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=master
  - FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com
